
server:
  port: 8086

spring:
  application:
    name: ConfigServer


  cloud:
   config:
     server:
       git:
         uri: https://github.com/1998931/config-server
         clone-on-start: true



