version: '3.8'

services:
  serviceregistry:
    image: springboot/serviceregistry:latest
    container_name: serviceregistry
    ports:
      - "8761:8761"

  ratingservice:
    image: ratingservice:latest
    container_name: ratingservice
    ports:
      - "8082:8082"
    depends_on:
      - serviceregistry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
